[phases.setup]
nixpkgsArchive = "f69ae4816bc1b501460ad2c0c63ed0cc4a9b876e"
nixPkgs = ["nodejs_22", "bun"]

[phases.install]
cmds = ["cd web && bun install"]

[phases.build]
cmds = ["cd web && bun run build"]

[start]
cmd = "cd web && bun run start"
